### ISSUE TITLE
Error during load

### ISSUE THREAD

**Issue by PaffcioStudio** [Litecrafty/Launcher#16]
**Anybody know what's going on?**

`paffcio@paffcio:~/Download/Launcher-master$ npm run start

> litecraft-launcher@0.1.0 start /home/paffcio/Download/Launcher-master
> electron .

App threw an error during load
TypeError: app.makeSingleInstance is not a function
    at Object.<anonymous> (/home/paffcio/Download/Launcher-master/index.js:15:30)
    at Module._compile (internal/modules/cjs/loader.js:808:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:820:10)
    at Module.load (internal/modules/cjs/loader.js:677:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:609:12)
    at Function.Module._load (internal/modules/cjs/loader.js:601:3)
    at loadApplicationPackage (/home/paffcio/Download/Launcher-master/node_modules/electron/dist/resources/default_app.asar/main.js:105:12)
    at Object.<anonymous> (/home/paffcio/Download/Launcher-master/node_modules/electron/dist/resources/default_app.asar/main.js:153:5)
    at Module._compile (internal/modules/cjs/loader.js:808:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:820:10)
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: app.makeSingleInstance is not a function
    at Object.<anonymous> (/home/paffcio/Download/Launcher-master/index.js:15:30)
    at Module._compile (internal/modules/cjs/loader.js:808:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:820:10)
    at Module.load (internal/modules/cjs/loader.js:677:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:609:12)
    at Function.Module._load (internal/modules/cjs/loader.js:601:3)
    at loadApplicationPackage (/home/paffcio/Download/Launcher-master/node_modules/electron/dist/resources/default_app.asar/main.js:105:12)
    at Object.<anonymous> (/home/paffcio/Download/Launcher-master/node_modules/electron/dist/resources/default_app.asar/main.js:153:5)
    at Module._compile (internal/modules/cjs/loader.js:808:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:820:10)

`

**Comment by AaronSezar** [comment]
Same issue
